version: '3.7'
services:
  sonardb:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    image: postgres
    # hostname: sonardb.pulse
    container_name: sonarqubedb-cicd
    restart: always
    environment:
      TZ: America/Fortaleza
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/dombarbosa/workspace/docker_volumes_backup/desafio-devops/sonar_volumes/postgresql:/var/lib/postgresql
      - /home/dombarbosa/workspace/docker_volumes_backup/desafio-devops/sonar_volumes/postgresql_data:/var/lib/postgresql/data
      # - /etc/hosts:/etc/hosts:ro
    networks:
      common-net:
        ipv4_address: 10.230.10.8

  sonarweb:
    deploy:
      resources:
        limits:
          memory: 3072M
        reservations:
          memory: 1024M
    image: sonarqube:latest
    depends_on:
      - sonardb
    # hostname: sonar.pulse
    container_name: sonarqube-cicd
    restart: always
    ports:
      - "9082:9000"
    environment:
      - TZ=America/Fortaleza
      - "SONAR_JDBC_USERNAME=sonarqube"
      - "SONAR_JDBC_PASSWORD=sonarqube"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/dombarbosa/workspace/docker_volumes_backup/desafio-devops/sonar_volumes/sonarqube_conf:/opt/sonarqube/conf
      - /home/dombarbosa/workspace/docker_volumes_backup/desafio-devops/sonar_volumes/sonarqube_data:/opt/sonarqube/data
      - /home/dombarbosa/workspace/docker_volumes_backup/desafio-devops/sonar_volumes/sonarqube_logs:/opt/sonarqube/logs
      - /home/dombarbosa/workspace/docker_volumes_backup/desafio-devops/sonar_volumes/sonarqube_extensions:/opt/sonarqube/extensions
      # - /etc/hosts:/etc/hosts:ro
    networks:
      common-net:
        ipv4_address: 10.230.10.7
networks:
  common-net:
    external: true