---
# - name: Entrega continua 
#   command: "docker ps"
- name: Deploy_com_ansible
  docker_container:
    name: appspring
    state: started
    restart: yes
    # image: {{ item }}
    # image: 'registry.pulse:5001/helloworld-prod:latest'
    image: '{{regL}}/{{aID}}:{{vs}}-{{envproj}}'
    # image: registry.pulse:5001/helloworld:{{vers}}-prod
    volumes:
      - 'appspring:/var/www/html/'
    cpu_quota: 100000
    exposed_ports: 
      - 8080:8080
    published_ports: 
      - 8080:8080
    memory: 1G